name: Split Learning
server:
  num-round: 1
  cut_layers:
    - 10
    - 20
  clients:
    - 1
    - 1
    - 1
  filename: resnet_model
  parameters:
    load: False
    save: False
  validation: False


rabbit:
  address: 192.168.101.234
  username: dai
  password: dai

log_path: .

learning:
  learning-rate: 0.01
  momentum: 1
  batch-size: 256
  control-count: 3
  validation: False
