name: Split Learning
server:
  num-round: 1
  cut_layers:
    - 10
    - 20
  clients:
    - 1
    - 1
    - 1
  model: VGG16
  parameters:
    load: False
    save: False
  validation: False

rabbit:
  address: rabbitmq
  username: admin
  password: admin

log_path: .

learning:
  learning-rate: 0.01
  momentum: 0.5
  batch-size: 128
  control-count: 3
