version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/limits.conf:/etc/security/limits.conf
    networks:
      - network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  server:
    image: quang47/server
    container_name: server
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    networks:
      - network
    command: ["sh", "-c", "sleep 7 && python server.py"]
    environment:
      - PYTHONUNBUFFERED=1

  client1:
    image: quang47/client
    container_name: client1
    depends_on:
      - rabbitmq
      - server
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    networks:
      - network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 1 --device cpu"]
    environment:
      - PYTHONUNBUFFERED=1

  client2:
    image: quang47/client
    container_name: client2
    depends_on:
      - rabbitmq
      - server
      - client1
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    networks:
      - network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 3 --device cpu"]
    environment:
      - PYTHONUNBUFFERED=1

  client3:
    image: quang47/client
    container_name: client3
    depends_on:
      - rabbitmq
      - server
      - client1
      - client2
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    networks:
      - network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 2 --device cpu"]
    environment:
      - PYTHONUNBUFFERED=1

networks:
  network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local

