apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-layer1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-layer1-pod
  template:
    metadata:
      labels:
        app: client-layer1-pod
    spec:
      containers:
      - name: client-layer1
        image: quang47/client
        command: ["/bin/sh", "-c", "sleep 20 && python client.py --layer_id 1 --device cpu"]
        volumeMounts:
        - name: client-config
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: client-config
        configMap: 
          name: split-learning-config