apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service 
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
  - name: mgmt-port
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: user-port
    protocol: TCP
    port: 15672
    targetPort: 15672